const productsArr = [
    {
      _id: "678be6b1e5490f222edeb520",
      name: "Weat Chokker",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 17,
      pricePerBag: 850,
      weightOfBag: 50,
      category: "Fodder Ingredient",
      description: "Product",
      isFodderIngredient: true,
      productCanBeAddedToFodder: false,
      isWhole: false,
      totalAvailableCount: 0,
      totalAvailableWeight: 1000,
      __v: 0,
    },
    {
      _id: "678be7dbe5490f222edeb522",
      name: "Gram Skin",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 20,
      pricePerBag: 950,
      weightOfBag: 50,
      category: "Fodder Ingredient",
      description: "Product",
      isFodderIngredient: true,
      productCanBeAddedToFodder: false,
      isWhole: false,
      totalAvailableCount: 0,
      totalAvailableWeight: 1000,
      __v: 0,
    },
    {
      _id: "678be800e5490f222edeb524",
      name: "Gram Powder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 16,
      pricePerBag: 750,
      weightOfBag: 50,
      category: "Fodder Ingredient",
      description: "Product",
      isFodderIngredient: true,
      productCanBeAddedToFodder: false,
      isWhole: false,
      totalAvailableCount: 0,
      totalAvailableWeight: 1000,
      __v: 0,
    },
    {
      _id: "678be819e5490f222edeb526",
      name: "Rice Polish",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 25,
      pricePerBag: 1150,
      weightOfBag: 50,
      category: "Fodder Ingredient",
      description: "Product",
      isFodderIngredient: true,
      productCanBeAddedToFodder: false,
      isWhole: false,
      totalAvailableCount: 0,
      totalAvailableWeight: 1000,
      __v: 0,
    },
    {
      _id: "678be8d5e5490f222edeb528",
      name: "CUD 10000 Green Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 28,
      pricePerBag: 1400,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678be8fae5490f222edeb52a",
      name: "CUD 8000 Green Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 25,
      pricePerBag: 1250,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678be91ae5490f222edeb52c",
      name: "CUD 10000 Red Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 30,
      pricePerBag: 1500,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678be930e5490f222edeb52e",
      name: "CUD 8000 Red Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 28,
      pricePerBag: 1400,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678be946e5490f222edeb530",
      name: "CUD 6000 Red Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 20,
      pricePerBag: 1000,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678be967e5490f222edeb532",
      name: "CUD 6000 Green Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 26,
      pricePerBag: 1300,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678be97be5490f222edeb534",
      name: "CUD 4000 Red Fodder",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 22,
      pricePerBag: 1100,
      weightOfBag: 50,
      category: "Our Products",
      description: "Our Product",
      isFodderIngredient: false,
      productCanBeAddedToFodder: false,
      isWhole: true,
      totalAvailableCount: 2000,
      totalAvailableWeight: 50000,
      __v: 0,
    },
    {
      _id: "678bea24e5490f222edeb536",
      name: "Metabolite 500g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1000,
      pricePerBag: 500,
      weightOfBag: 0.5,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 500,
      __v: 0,
    },
    {
      _id: "678bea3fe5490f222edeb538",
      name: "Metabolite Calf 500g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1200,
      pricePerBag: 600,
      weightOfBag: 0.5,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 500,
      __v: 0,
    },
    {
      _id: "678bea51e5490f222edeb53a",
      name: "Metabolite Cow 500g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1400,
      pricePerBag: 700,
      weightOfBag: 0.5,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 500,
      __v: 0,
    },
    {
      _id: "678bea6be5490f222edeb53c",
      name: "Metabolite Horse 500g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1500,
      pricePerBag: 750,
      weightOfBag: 0.5,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 500,
      __v: 0,
    },
    {
      _id: "678beaace5490f222edeb53e",
      name: "Udderstrong 200g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1000,
      pricePerBag: 200,
      weightOfBag: 0.2,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 200,
      __v: 0,
    },
    {
      _id: "678bead3e5490f222edeb540",
      name: "Udderstrong Plus 200g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1200,
      pricePerBag: 240,
      weightOfBag: 0.2,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 200,
      __v: 0,
    },
    {
      _id: "678beae4e5490f222edeb542",
      name: "Calcinite 200g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1200,
      pricePerBag: 240,
      weightOfBag: 0.2,
      category: "Medicines",
      description: "Medicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 200,
      __v: 0,
    },
    {
      _id: "678beaefe5490f222edeb544",
      name: "Empirio 200g",
      imageUrl:
        "https://www.nicepng.com/png/detail/257-2574100_kamdhenu-cow-with-calf-working-animal.png",
      pricePerKg: 1200,
      pricePerBag: 240,
      weightOfBag: 0.2,
      category: "Medicines",
      description: "MedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicineMedicine",
      isFodderIngredient: false,
      productCanBeAddedToFodder: true,
      isWhole: true,
      totalAvailableCount: 1000,
      totalAvailableWeight: 200,
      __v: 0,
    },
  ];

  export default productsArr;